### ISSUE TITLE
Gas cost of claiming usdc from veNFT is very high

### ISSUE THREAD

**Issue by jokie88** [anyswap/veMULTI#4]
OK so I might be completely wrong here, but I am seeing that the gas fee for claiming is very very high.

Lets take this transaction for example: 
https://rinkeby.etherscan.io/tx/0x4f7553b1fa22ce3a1ffa3e2e3ff182dade053f740b7060bdccbd206ccf841e84

and assume realistic base fee and priority fees: 50 base fee, 2.1 priority fee. I took this from a recent transaction I did and if anything, I would say its on the low side. 

gas usage * (base fee + priority fee) = 3,613,080 * (50 + 2.1) = 188241468 GWEI = 0.17 eth = $473 USD! 

These costs would make it uneconomical for a lot of people to stake. For example, if we assume we want to keep gas cost at 5% of the amount withdrawn, you would need to wait until you have  $10,000 to withdraw. Averaging out across the decline in ve power, I imagine you need over 250,000 USD minimum for locking to make sense with a quarterly withdrawal.

(PS I could be very wrong w/ my gas fee calculations -- i've never done them before so I am not sure i'm doing it correctly)

**Comment by zhaojun-sh** [comment]
The veMULTI reward cycle is half an hour on Rinkeby testnet, and it's one week on mainnet.
The gas limit cost per cycle is ~50k, so it will be 300k gas limit to claim month reward,  and 2.5m gas limit per year.

**Comment by jokie88** [comment]
aah i see interesting. so the for loop is most of the gas cost and depends on the number of Epochs the code has to go through. so in some ways, a strategy of claiming less often doesn't help too much. 

that is helpful to understand. thanks.

**Comment by jokie88** [comment]
so about 114,500 base gas to run, plus 50k for every additional epoch. thanks!
